// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Read(arg1:string):Promise<string>;

export function Write(arg1:string):Promise<string>;
