// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAndInstallDaemon():Promise<string>;

export function CheckBlocking():Promise<boolean>;

export function CheckDaemonInstalled():Promise<boolean>;

export function ConnectToDaemon():Promise<string>;

export function ExtractDaemonBinary():Promise<string>;

export function GetDaemonBinaryDestination():Promise<string>;

export function GetDaemonBinaryPath():Promise<string>;

export function HostsFilePath():Promise<string>;

export function InstallAndStartDaemon():Promise<string>;

export function InstallDaemonBinary():Promise<string>;

export function InstallDaemonWithOneClick():Promise<string>;

export function LoadBlockedWebsites():Promise<string>;

export function SaveBlockedWebsites(arg1:string):Promise<boolean>;

export function SendBlockList(arg1:string):Promise<boolean>;

export function StartBlocking():Promise<boolean>;

export function StopBlocking():Promise<string>;

export function WriteToHostFile():Promise<string>;
