// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAndInstallDaemon() {
  return window['go']['main']['App']['CheckAndInstallDaemon']();
}

export function CheckBlocking() {
  return window['go']['main']['App']['CheckBlocking']();
}

export function CheckDaemonInstalled() {
  return window['go']['main']['App']['CheckDaemonInstalled']();
}

export function ConnectToDaemon() {
  return window['go']['main']['App']['ConnectToDaemon']();
}

export function ExtractDaemonBinary() {
  return window['go']['main']['App']['ExtractDaemonBinary']();
}

export function GetDaemonBinaryDestination() {
  return window['go']['main']['App']['GetDaemonBinaryDestination']();
}

export function GetDaemonBinaryPath() {
  return window['go']['main']['App']['GetDaemonBinaryPath']();
}

export function HostsFilePath() {
  return window['go']['main']['App']['HostsFilePath']();
}

export function InstallAndStartDaemon() {
  return window['go']['main']['App']['InstallAndStartDaemon']();
}

export function InstallDaemonBinary() {
  return window['go']['main']['App']['InstallDaemonBinary']();
}

export function InstallDaemonWithOneClick() {
  return window['go']['main']['App']['InstallDaemonWithOneClick']();
}

export function LoadBlockedWebsites() {
  return window['go']['main']['App']['LoadBlockedWebsites']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function SaveBlockedWebsites(arg1) {
  return window['go']['main']['App']['SaveBlockedWebsites'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SendBlockList(arg1) {
  return window['go']['main']['App']['SendBlockList'](arg1);
}

export function StartBlocking() {
  return window['go']['main']['App']['StartBlocking']();
}

export function StopBlocking() {
  return window['go']['main']['App']['StopBlocking']();
}

export function WriteToHostFile() {
  return window['go']['main']['App']['WriteToHostFile']();
}
