// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HostsFilePath() {
  return window['go']['main']['App']['HostsFilePath']();
}

export function Read(arg1) {
  return window['go']['main']['App']['Read'](arg1);
}

export function Write(arg1) {
  return window['go']['main']['App']['Write'](arg1);
}

export function WriteToHostFile() {
  return window['go']['main']['App']['WriteToHostFile']();
}
