name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: asdf-vm/actions/setup@v3

      - uses: asdf-vm/actions/install@v3

      - name: Install Go dependencies
        run: go mod download

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: asdf-vm/actions/setup@v3

      - uses: asdf-vm/actions/install@v3

      - name: Install npm dependencies
        run: npm ci
        working-directory: frontend

      - name: Lint
        run: npm run lint
        working-directory: frontend

      - name: Build
        run: npm run build
        working-directory: frontend

      - name: Test
        run: npm run test
        working-directory: frontend
